# Generated by Django 3.2.4 on 2026-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, verbose_name='Bus Brand')),
                ('model', models.CharField(max_length=15, verbose_name='Bus Model')),
                ('plate_No', models.CharField(max_length=15, unique=True, verbose_name='Plate No.')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/')),
                ('available', models.BooleanField(default=True)),
                ('seats_Sold', models.PositiveIntegerField(default=0)),
                ('available_Seat', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('departure_Date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('departure_Time', models.TimeField(blank=True, default='00:00:00')),
                ('time_Session', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Seat',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('TP-Cash', 'TP-Cash'), ('MoMo', 'MoMo')], default='MoMo', max_length=8)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bus')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='company.place', verbose_name='Destination From')),
                ('D_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='company.place', verbose_name='Destination To')),
            ],
        ),
        migrations.CreateModel(
            name='Cancelled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Date', models.DateTimeField(auto_now_add=True)),
                ('TP_cash', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.destination'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.driver'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Date', models.DateField(auto_now_add=True)),
                ('book_Time', models.TimeField(auto_now_add=True)),
                ('ticket_user', models.CharField(default='', max_length=50)),
                ('seat', models.CharField(max_length=120)),
                ('driver', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('destination', models.CharField(max_length=100)),
                ('departure_Date', models.DateField()),
                ('time_Session', models.CharField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='images/qr_codes/')),
                ('book_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-use', 'In-use'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Active', max_length=15)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientprofile', verbose_name='Client')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Date', models.DateField(auto_now_add=True)),
                ('book_Time', models.TimeField(auto_now_add=True)),
                ('ticket_user', models.CharField(default='', max_length=50)),
                ('seat', models.CharField(max_length=120)),
                ('driver', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('destination', models.CharField(max_length=50)),
                ('departure_Date', models.DateField()),
                ('time_Session', models.CharField(max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientprofile', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
        ),
    ]
