# Generated by Django 3.2.4 on 2026-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('company_initials', models.CharField(max_length=3, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('seat_selection', models.CharField(choices=[('Random', 'Random'), ('Selected', 'Selected')], default='Random', max_length=9)),
                ('contact_1', models.CharField(max_length=20, verbose_name='Contact 1')),
                ('contact_2', models.CharField(blank=True, max_length=20, verbose_name='Contact 2')),
                ('contact_3', models.CharField(blank=True, max_length=20, verbose_name='Contact 3')),
                ('contact_4', models.CharField(blank=True, max_length=20, verbose_name='Contact 4')),
                ('userid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('long', models.CharField(max_length=50, verbose_name='Longitude')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=20, verbose_name='Phone 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 2')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.staffprofile')),
            ],
        ),
    ]
